"""Initial migration

Revision ID: 3b7c8076502f
Revises: 
Create Date: 2024-03-07 21:48:35.692095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7c8076502f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clap_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.drop_column('clap_count')

    # ### end Alembic commands ###
